# Generated by Django 5.0 on 2023-12-26 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('StudentId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('EducationLevel', models.CharField(choices=[('primary', 'Primary'), ('high_school', 'High School'), ('college', 'College'), ('diploma', 'Diploma'), ('bsc', 'BSc'), ('honurs', 'Honours'), ('bba', 'BBA')], max_length=100)),
                ('EnrollmentDate', models.DateField(default=django.utils.timezone.now)),
                ('OfficialPicture', models.ImageField(upload_to='./app/Files/')),
                ('Resume', models.FileField(upload_to='')),
            ],
        ),
    ]
