# Generated by Django 5.0 on 2023-12-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentmodel_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='EnrollmentDate',
            field=models.DateField(),
        ),
    ]
