# Generated by Django 5.0 on 2023-12-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentmodel_enrollmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='OfficialPicture',
            field=models.ImageField(upload_to='app/Files/'),
        ),
    ]
